# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='config',
            field=models.CharField(blank=True, choices=[('slideshows/slides_show/configs/default.html', 'Default config')], default='', help_text='The Javascript config file to use to configure and initialize the slideshow', max_length=100, verbose_name='config template'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='template',
            field=models.CharField(choices=[('slideshows/slides_show/default.html', 'Default template')], default='slideshows/slides_show/default.html', max_length=100, verbose_name='content template'),
        ),
    ]
