# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0002_auto_20170208_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='config',
            field=models.CharField(blank=True, choices=[('slideshows/slides_show/configs/default.html', 'Default config'), ('slideshows/slides_show/configs/bootstrap_3.html', 'Bootstrap 3 config')], default='', help_text='The Javascript config file to use to configure and initialize the slideshow', max_length=100, verbose_name='config template'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='template',
            field=models.CharField(choices=[('slideshows/slides_show/default.html', 'Default template'), ('slideshows/slides_show/bootstrap_3.html', 'Bootstrap 3 template')], default='slideshows/slides_show/default.html', max_length=100, verbose_name='content template'),
        ),
    ]
