# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0003_auto_20170210_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image_url_link',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True, help_text='Adds url link to image', verbose_name='linkable image'),
        ),
        migrations.AddField(
            model_name='slide',
            name='show_content',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True, verbose_name='show content'),
        ),
        migrations.AddField(
            model_name='slide',
            name='show_title',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True, verbose_name='show tittle'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_url_link',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True, help_text='Adds url link to title', verbose_name='linkable title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='publish',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True, help_text='Unpublished slide will not be displayed in its slideshow', verbose_name='published'),
        ),
    ]
