# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshows', '0004_auto_20170223_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_url_link',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title_url_link',
        ),
        migrations.AddField(
            model_name='slide',
            name='linkable_image',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Adds url link to image, if there is url', verbose_name='linkable image'),
        ),
        migrations.AddField(
            model_name='slide',
            name='linkable_title',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Adds url link to title, if there is url', verbose_name='linkable title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='publish',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Unpublished slide will not be displayed in its slideshow', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='show_content',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='If there is content', verbose_name='show content'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='show_title',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='show tittle'),
        ),
    ]
